version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: shuttersync-postgres
    environment:
      POSTGRES_USER: siaw
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shuttersync
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
